spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:h2:mem:auth-resource
    username: sa
    password: password
    driverClassName: org.h2.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.H2Dialect
          format_sql: true
      hibernate:
        ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2-console

